export const movies: Array<{
  url: string
  title: string
  releaseYear: number
  runtimeSeconds: number
  certificate?: string
}> = [
  {
    url: 'https://www.imdb.com/title/tt0111161',
    title: 'The Shawshank Redemption',
    releaseYear: 1994,
    runtimeSeconds: 8520,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0068646',
    title: 'The Godfather',
    releaseYear: 1972,
    runtimeSeconds: 10500,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0468569',
    title: 'The Dark Knight',
    releaseYear: 2008,
    runtimeSeconds: 9120,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0071562',
    title: 'The Godfather Part II',
    releaseYear: 1974,
    runtimeSeconds: 12120,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0050083',
    title: '12 Angry Men',
    releaseYear: 1957,
    runtimeSeconds: 5760,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt0108052',
    title: "Schindler's List",
    releaseYear: 1993,
    runtimeSeconds: 11700,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0167260',
    title: 'The Lord of the Rings: The Return of the King',
    releaseYear: 2003,
    runtimeSeconds: 12060,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0110912',
    title: 'Pulp Fiction',
    releaseYear: 1994,
    runtimeSeconds: 9240,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0120737',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    releaseYear: 2001,
    runtimeSeconds: 10680,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0060196',
    title: 'The Good, the Bad and the Ugly',
    releaseYear: 1966,
    runtimeSeconds: 10680,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt0109830',
    title: 'Forrest Gump',
    releaseYear: 1994,
    runtimeSeconds: 8520,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0137523',
    title: 'Fight Club',
    releaseYear: 1999,
    runtimeSeconds: 8340,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0167261',
    title: 'The Lord of the Rings: The Two Towers',
    releaseYear: 2002,
    runtimeSeconds: 10740,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt1375666',
    title: 'Inception',
    releaseYear: 2010,
    runtimeSeconds: 8880,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0080684',
    title: 'Star Wars: Episode V - The Empire Strikes Back',
    releaseYear: 1980,
    runtimeSeconds: 7440,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0133093',
    title: 'The Matrix',
    releaseYear: 1999,
    runtimeSeconds: 8160,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0099685',
    title: 'Goodfellas',
    releaseYear: 1990,
    runtimeSeconds: 8700,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0073486',
    title: "One Flew Over the Cuckoo's Nest",
    releaseYear: 1975,
    runtimeSeconds: 7980,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0114369',
    title: 'Se7en',
    releaseYear: 1995,
    runtimeSeconds: 7620,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0038650',
    title: "It's a Wonderful Life",
    releaseYear: 1946,
    runtimeSeconds: 7800,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0047478',
    title: 'Seven Samurai',
    releaseYear: 1954,
    runtimeSeconds: 12420,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0816692',
    title: 'Interstellar',
    releaseYear: 2014,
    runtimeSeconds: 10140,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0102926',
    title: 'The Silence of the Lambs',
    releaseYear: 1991,
    runtimeSeconds: 7080,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt9362722',
    title: 'Spider-Man: Across the Spider-Verse',
    releaseYear: 2023,
    runtimeSeconds: 8400,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0120815',
    title: 'Saving Private Ryan',
    releaseYear: 1998,
    runtimeSeconds: 10140,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0317248',
    title: 'City of God',
    releaseYear: 2002,
    runtimeSeconds: 7800,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0118799',
    title: 'Life Is Beautiful',
    releaseYear: 1997,
    runtimeSeconds: 6960,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0120689',
    title: 'The Green Mile',
    releaseYear: 1999,
    runtimeSeconds: 11340,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0076759',
    title: 'Star Wars: Episode IV - A New Hope',
    releaseYear: 1977,
    runtimeSeconds: 7260,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0103064',
    title: 'Terminator 2: Judgment Day',
    releaseYear: 1991,
    runtimeSeconds: 8220,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0088763',
    title: 'Back to the Future',
    releaseYear: 1985,
    runtimeSeconds: 6960,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0245429',
    title: 'Spirited Away',
    releaseYear: 2001,
    runtimeSeconds: 7500,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0253474',
    title: 'The Pianist',
    releaseYear: 2002,
    runtimeSeconds: 9000,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0054215',
    title: 'Psycho',
    releaseYear: 1960,
    runtimeSeconds: 6540,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt6751668',
    title: 'Parasite',
    releaseYear: 2019,
    runtimeSeconds: 7920,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0172495',
    title: 'Gladiator',
    releaseYear: 2000,
    runtimeSeconds: 9300,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0110357',
    title: 'The Lion King',
    releaseYear: 1994,
    runtimeSeconds: 5280,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0110413',
    title: 'Léon: The Professional',
    releaseYear: 1994,
    runtimeSeconds: 6600,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0120586',
    title: 'American History X',
    releaseYear: 1998,
    runtimeSeconds: 7140,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0407887',
    title: 'The Departed',
    releaseYear: 2006,
    runtimeSeconds: 9060,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt2582802',
    title: 'Whiplash',
    releaseYear: 2014,
    runtimeSeconds: 6360,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0482571',
    title: 'The Prestige',
    releaseYear: 2006,
    runtimeSeconds: 7800,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0114814',
    title: 'The Usual Suspects',
    releaseYear: 1995,
    runtimeSeconds: 6360,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0095327',
    title: 'Grave of the Fireflies',
    releaseYear: 1988,
    runtimeSeconds: 5340,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0056058',
    title: 'Harakiri',
    releaseYear: 1962,
    runtimeSeconds: 7980,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0034583',
    title: 'Casablanca',
    releaseYear: 1942,
    runtimeSeconds: 6120,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt15398776',
    title: 'Oppenheimer',
    releaseYear: 2023,
    runtimeSeconds: 10800,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt1675434',
    title: 'The Intouchables',
    releaseYear: 2011,
    runtimeSeconds: 6720,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0027977',
    title: 'Modern Times',
    releaseYear: 1936,
    runtimeSeconds: 5220,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0095765',
    title: 'Cinema Paradiso',
    releaseYear: 1988,
    runtimeSeconds: 9300,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0064116',
    title: 'Once Upon a Time in the West',
    releaseYear: 1968,
    runtimeSeconds: 9900,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0047396',
    title: 'Rear Window',
    releaseYear: 1954,
    runtimeSeconds: 6720,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0078748',
    title: 'Alien',
    releaseYear: 1979,
    runtimeSeconds: 7020,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0021749',
    title: 'City Lights',
    releaseYear: 1931,
    runtimeSeconds: 5220,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0078788',
    title: 'Apocalypse Now',
    releaseYear: 1979,
    runtimeSeconds: 8820,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0209144',
    title: 'Memento',
    releaseYear: 2000,
    runtimeSeconds: 6780,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt1853728',
    title: 'Django Unchained',
    releaseYear: 2012,
    runtimeSeconds: 9900,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0082971',
    title: 'Raiders of the Lost Ark',
    releaseYear: 1981,
    runtimeSeconds: 6900,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0910970',
    title: 'WALL·E',
    releaseYear: 2008,
    runtimeSeconds: 5880,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0405094',
    title: 'The Lives of Others',
    releaseYear: 2006,
    runtimeSeconds: 8220,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0043014',
    title: 'Sunset Blvd.',
    releaseYear: 1950,
    runtimeSeconds: 6600,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0050825',
    title: 'Paths of Glory',
    releaseYear: 1957,
    runtimeSeconds: 5280,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt4154756',
    title: 'Avengers: Infinity War',
    releaseYear: 2018,
    runtimeSeconds: 8940,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0081505',
    title: 'The Shining',
    releaseYear: 1980,
    runtimeSeconds: 8760,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0032553',
    title: 'The Great Dictator',
    releaseYear: 1940,
    runtimeSeconds: 7500,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0051201',
    title: 'Witness for the Prosecution',
    releaseYear: 1957,
    runtimeSeconds: 6960,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt4633694',
    title: 'Spider-Man: Into the Spider-Verse',
    releaseYear: 2018,
    runtimeSeconds: 7020,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0090605',
    title: 'Aliens',
    releaseYear: 1986,
    runtimeSeconds: 8220,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0361748',
    title: 'Inglourious Basterds',
    releaseYear: 2009,
    runtimeSeconds: 9180,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt1345836',
    title: 'The Dark Knight Rises',
    releaseYear: 2012,
    runtimeSeconds: 9840,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0169547',
    title: 'American Beauty',
    releaseYear: 1999,
    runtimeSeconds: 7320,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0057012',
    title:
      'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
    releaseYear: 1964,
    runtimeSeconds: 5700,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0364569',
    title: 'Oldboy',
    releaseYear: 2003,
    runtimeSeconds: 7200,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt2380307',
    title: 'Coco',
    releaseYear: 2017,
    runtimeSeconds: 6300,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0086879',
    title: 'Amadeus',
    releaseYear: 1984,
    runtimeSeconds: 9600,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0114709',
    title: 'Toy Story',
    releaseYear: 1995,
    runtimeSeconds: 4860,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0082096',
    title: 'Das Boot',
    releaseYear: 1981,
    runtimeSeconds: 8940,
  },
  {
    url: 'https://www.imdb.com/title/tt0112573',
    title: 'Braveheart',
    releaseYear: 1995,
    runtimeSeconds: 10680,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt4154796',
    title: 'Avengers: Endgame',
    releaseYear: 2019,
    runtimeSeconds: 10860,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt7286456',
    title: 'Joker',
    releaseYear: 2019,
    runtimeSeconds: 7320,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0119698',
    title: 'Princess Mononoke',
    releaseYear: 1997,
    runtimeSeconds: 8040,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0119217',
    title: 'Good Will Hunting',
    releaseYear: 1997,
    runtimeSeconds: 7560,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt5311514',
    title: 'Your Name.',
    releaseYear: 2016,
    runtimeSeconds: 6360,
    certificate: 'TV-PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0087843',
    title: 'Once Upon a Time in America',
    releaseYear: 1984,
    runtimeSeconds: 13740,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt1187043',
    title: '3 Idiots',
    releaseYear: 2009,
    runtimeSeconds: 10200,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0057565',
    title: 'High and Low',
    releaseYear: 1963,
    runtimeSeconds: 8580,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0045152',
    title: "Singin' in the Rain",
    releaseYear: 1952,
    runtimeSeconds: 6180,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt8267604',
    title: 'Capernaum',
    releaseYear: 2018,
    runtimeSeconds: 7560,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0180093',
    title: 'Requiem for a Dream',
    releaseYear: 2000,
    runtimeSeconds: 6120,
    certificate: 'Unrated',
  },
  {
    url: 'https://www.imdb.com/title/tt0435761',
    title: 'Toy Story 3',
    releaseYear: 2010,
    runtimeSeconds: 6180,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0091251',
    title: 'Come and See',
    releaseYear: 1985,
    runtimeSeconds: 8520,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0086190',
    title: 'Star Wars: Episode VI - Return of the Jedi',
    releaseYear: 1983,
    runtimeSeconds: 7860,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0338013',
    title: 'Eternal Sunshine of the Spotless Mind',
    releaseYear: 2004,
    runtimeSeconds: 6480,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0062622',
    title: '2001: A Space Odyssey',
    releaseYear: 1968,
    runtimeSeconds: 8940,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt2106476',
    title: 'The Hunt',
    releaseYear: 2012,
    runtimeSeconds: 6900,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0105236',
    title: 'Reservoir Dogs',
    releaseYear: 1992,
    runtimeSeconds: 5940,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0044741',
    title: 'Ikiru',
    releaseYear: 1952,
    runtimeSeconds: 8580,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0056172',
    title: 'Lawrence of Arabia',
    releaseYear: 1962,
    runtimeSeconds: 13080,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt0033467',
    title: 'Citizen Kane',
    releaseYear: 1941,
    runtimeSeconds: 7140,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0053604',
    title: 'The Apartment',
    releaseYear: 1960,
    runtimeSeconds: 7500,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt0022100',
    title: 'M',
    releaseYear: 1931,
    runtimeSeconds: 5940,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0053125',
    title: 'North by Northwest',
    releaseYear: 1959,
    runtimeSeconds: 8160,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt0052357',
    title: 'Vertigo',
    releaseYear: 1958,
    runtimeSeconds: 7680,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0036775',
    title: 'Double Indemnity',
    releaseYear: 1944,
    runtimeSeconds: 6420,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0211915',
    title: 'Amélie',
    releaseYear: 2001,
    runtimeSeconds: 7320,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0086250',
    title: 'Scarface',
    releaseYear: 1983,
    runtimeSeconds: 10200,
    certificate: '18+',
  },
  {
    url: 'https://www.imdb.com/title/tt0093058',
    title: 'Full Metal Jacket',
    releaseYear: 1987,
    runtimeSeconds: 6960,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0066921',
    title: 'A Clockwork Orange',
    releaseYear: 1971,
    runtimeSeconds: 8160,
    certificate: 'X',
  },
  {
    url: 'https://www.imdb.com/title/tt1255953',
    title: 'Incendies',
    releaseYear: 2010,
    runtimeSeconds: 7860,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0113277',
    title: 'Heat',
    releaseYear: 1995,
    runtimeSeconds: 10200,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt1049413',
    title: 'Up',
    releaseYear: 2009,
    runtimeSeconds: 5760,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt8503618',
    title: 'Hamilton',
    releaseYear: 2020,
    runtimeSeconds: 9600,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0056592',
    title: 'To Kill a Mockingbird',
    releaseYear: 1962,
    runtimeSeconds: 7740,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt0070735',
    title: 'The Sting',
    releaseYear: 1973,
    runtimeSeconds: 7740,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt1832382',
    title: 'A Separation',
    releaseYear: 2011,
    runtimeSeconds: 7380,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0097576',
    title: 'Indiana Jones and the Last Crusade',
    releaseYear: 1989,
    runtimeSeconds: 7620,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0017136',
    title: 'Metropolis',
    releaseYear: 1927,
    runtimeSeconds: 9180,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0095016',
    title: 'Die Hard',
    releaseYear: 1988,
    runtimeSeconds: 7920,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0986264',
    title: 'Like Stars on Earth',
    releaseYear: 2007,
    runtimeSeconds: 9720,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0208092',
    title: 'Snatch',
    releaseYear: 2000,
    runtimeSeconds: 6120,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0040522',
    title: 'Bicycle Thieves',
    releaseYear: 1948,
    runtimeSeconds: 5340,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0119488',
    title: 'L.A. Confidential',
    releaseYear: 1997,
    runtimeSeconds: 8280,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0075314',
    title: 'Taxi Driver',
    releaseYear: 1976,
    runtimeSeconds: 6840,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt8579674',
    title: '1917',
    releaseYear: 2019,
    runtimeSeconds: 7140,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0363163',
    title: 'Downfall',
    releaseYear: 2004,
    runtimeSeconds: 9360,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt5074352',
    title: 'Dangal',
    releaseYear: 2016,
    runtimeSeconds: 9660,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0059578',
    title: 'For a Few Dollars More',
    releaseYear: 1965,
    runtimeSeconds: 7920,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0372784',
    title: 'Batman Begins',
    releaseYear: 2005,
    runtimeSeconds: 8400,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt1745960',
    title: 'Top Gun: Maverick',
    releaseYear: 2022,
    runtimeSeconds: 7800,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0053291',
    title: 'Some Like It Hot',
    releaseYear: 1959,
    runtimeSeconds: 7260,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0012349',
    title: 'The Kid',
    releaseYear: 1921,
    runtimeSeconds: 4080,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0993846',
    title: 'The Wolf of Wall Street',
    releaseYear: 2013,
    runtimeSeconds: 10800,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt10272386',
    title: 'The Father',
    releaseYear: 2020,
    runtimeSeconds: 5820,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt6966692',
    title: 'Green Book',
    releaseYear: 2018,
    runtimeSeconds: 7800,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0042192',
    title: 'All About Eve',
    releaseYear: 1950,
    runtimeSeconds: 8280,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0055031',
    title: 'Judgment at Nuremberg',
    releaseYear: 1961,
    runtimeSeconds: 10740,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt0120382',
    title: 'The Truman Show',
    releaseYear: 1998,
    runtimeSeconds: 6180,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0469494',
    title: 'There Will Be Blood',
    releaseYear: 2007,
    runtimeSeconds: 9480,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0112641',
    title: 'Casino',
    releaseYear: 1995,
    runtimeSeconds: 10680,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0089881',
    title: 'Ran',
    releaseYear: 1985,
    runtimeSeconds: 9600,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt1130884',
    title: 'Shutter Island',
    releaseYear: 2010,
    runtimeSeconds: 8280,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0457430',
    title: "Pan's Labyrinth",
    releaseYear: 2006,
    runtimeSeconds: 7080,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0167404',
    title: 'The Sixth Sense',
    releaseYear: 1999,
    runtimeSeconds: 6420,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0107290',
    title: 'Jurassic Park',
    releaseYear: 1993,
    runtimeSeconds: 7620,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0105695',
    title: 'Unforgiven',
    releaseYear: 1992,
    runtimeSeconds: 7800,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0268978',
    title: 'A Beautiful Mind',
    releaseYear: 2001,
    runtimeSeconds: 8100,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0040897',
    title: 'The Treasure of the Sierra Madre',
    releaseYear: 1948,
    runtimeSeconds: 7560,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0055630',
    title: 'Yojimbo',
    releaseYear: 1961,
    runtimeSeconds: 6600,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0477348',
    title: 'No Country for Old Men',
    releaseYear: 2007,
    runtimeSeconds: 7320,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0266697',
    title: 'Kill Bill: Vol. 1',
    releaseYear: 2003,
    runtimeSeconds: 6660,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0071853',
    title: 'Monty Python and the Holy Grail',
    releaseYear: 1975,
    runtimeSeconds: 5460,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0084787',
    title: 'The Thing',
    releaseYear: 1982,
    runtimeSeconds: 6540,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0057115',
    title: 'The Great Escape',
    releaseYear: 1963,
    runtimeSeconds: 10320,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt0266543',
    title: 'Finding Nemo',
    releaseYear: 2003,
    runtimeSeconds: 6000,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0042876',
    title: 'Rashomon',
    releaseYear: 1950,
    runtimeSeconds: 5280,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0080678',
    title: 'The Elephant Man',
    releaseYear: 1980,
    runtimeSeconds: 7440,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0071315',
    title: 'Chinatown',
    releaseYear: 1974,
    runtimeSeconds: 7800,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0347149',
    title: "Howl's Moving Castle",
    releaseYear: 2004,
    runtimeSeconds: 7140,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0046912',
    title: 'Dial M for Murder',
    releaseYear: 1954,
    runtimeSeconds: 6300,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0031381',
    title: 'Gone with the Wind',
    releaseYear: 1939,
    runtimeSeconds: 14280,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0434409',
    title: 'V for Vendetta',
    releaseYear: 2005,
    runtimeSeconds: 7920,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0081398',
    title: 'Raging Bull',
    releaseYear: 1980,
    runtimeSeconds: 7740,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt1392214',
    title: 'Prisoners',
    releaseYear: 2013,
    runtimeSeconds: 9180,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0120735',
    title: 'Lock, Stock and Two Smoking Barrels',
    releaseYear: 1998,
    runtimeSeconds: 6420,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt1305806',
    title: 'The Secret in Their Eyes',
    releaseYear: 2009,
    runtimeSeconds: 7740,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt2096673',
    title: 'Inside Out',
    releaseYear: 2015,
    runtimeSeconds: 5700,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt10872600',
    title: 'Spider-Man: No Way Home',
    releaseYear: 2021,
    runtimeSeconds: 8880,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt5027774',
    title: 'Three Billboards Outside Ebbing, Missouri',
    releaseYear: 2017,
    runtimeSeconds: 6900,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0050212',
    title: 'The Bridge on the River Kwai',
    releaseYear: 1957,
    runtimeSeconds: 9660,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0117951',
    title: 'Trainspotting',
    releaseYear: 1996,
    runtimeSeconds: 5580,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0116282',
    title: 'Fargo',
    releaseYear: 1996,
    runtimeSeconds: 5880,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt1291584',
    title: 'Warrior',
    releaseYear: 2011,
    runtimeSeconds: 8400,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt1205489',
    title: 'Gran Torino',
    releaseYear: 2008,
    runtimeSeconds: 6960,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0264464',
    title: 'Catch Me If You Can',
    releaseYear: 2002,
    runtimeSeconds: 8460,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0096283',
    title: 'My Neighbor Totoro',
    releaseYear: 1988,
    runtimeSeconds: 5160,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0405159',
    title: 'Million Dollar Baby',
    releaseYear: 2004,
    runtimeSeconds: 7920,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt4729430',
    title: 'Klaus',
    releaseYear: 2019,
    runtimeSeconds: 5760,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt1201607',
    title: 'Harry Potter and the Deathly Hallows: Part 2',
    releaseYear: 2011,
    runtimeSeconds: 7800,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0118849',
    title: 'Children of Heaven',
    releaseYear: 1997,
    runtimeSeconds: 5340,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0083658',
    title: 'Blade Runner',
    releaseYear: 1982,
    runtimeSeconds: 7020,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt2024544',
    title: '12 Years a Slave',
    releaseYear: 2013,
    runtimeSeconds: 8040,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0112471',
    title: 'Before Sunrise',
    releaseYear: 1995,
    runtimeSeconds: 6060,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt2278388',
    title: 'The Grand Budapest Hotel',
    releaseYear: 2014,
    runtimeSeconds: 5940,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0015864',
    title: 'The Gold Rush',
    releaseYear: 1925,
    runtimeSeconds: 5700,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0052618',
    title: 'Ben-Hur',
    releaseYear: 1959,
    runtimeSeconds: 12720,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0072684',
    title: 'Barry Lyndon',
    releaseYear: 1975,
    runtimeSeconds: 11100,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt2267998',
    title: 'Gone Girl',
    releaseYear: 2014,
    runtimeSeconds: 8940,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt2119532',
    title: 'Hacksaw Ridge',
    releaseYear: 2016,
    runtimeSeconds: 8340,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0047296',
    title: 'On the Waterfront',
    releaseYear: 1954,
    runtimeSeconds: 6480,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt0107207',
    title: 'In the Name of the Father',
    releaseYear: 1993,
    runtimeSeconds: 7980,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0353969',
    title: 'Memories of Murder',
    releaseYear: 2003,
    runtimeSeconds: 7920,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0017925',
    title: 'The General',
    releaseYear: 1926,
    runtimeSeconds: 4680,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0077416',
    title: 'The Deer Hunter',
    releaseYear: 1978,
    runtimeSeconds: 10980,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0050986',
    title: 'Wild Strawberries',
    releaseYear: 1957,
    runtimeSeconds: 5460,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0041959',
    title: 'The Third Man',
    releaseYear: 1949,
    runtimeSeconds: 5580,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt3011894',
    title: 'Wild Tales',
    releaseYear: 2014,
    runtimeSeconds: 7320,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0046268',
    title: 'The Wages of Fear',
    releaseYear: 1953,
    runtimeSeconds: 7860,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0015324',
    title: 'Sherlock Jr.',
    releaseYear: 1924,
    runtimeSeconds: 2700,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0097165',
    title: 'Dead Poets Society',
    releaseYear: 1989,
    runtimeSeconds: 7680,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt1392190',
    title: 'Mad Max: Fury Road',
    releaseYear: 2015,
    runtimeSeconds: 7200,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0198781',
    title: 'Monsters, Inc.',
    releaseYear: 2001,
    runtimeSeconds: 5520,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0031679',
    title: 'Mr. Smith Goes to Washington',
    releaseYear: 1939,
    runtimeSeconds: 7740,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0073195',
    title: 'Jaws',
    releaseYear: 1975,
    runtimeSeconds: 7440,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0892769',
    title: 'How to Train Your Dragon',
    releaseYear: 2010,
    runtimeSeconds: 5880,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0978762',
    title: 'Mary and Max',
    releaseYear: 2009,
    runtimeSeconds: 5520,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0050976',
    title: 'The Seventh Seal',
    releaseYear: 1957,
    runtimeSeconds: 5760,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt1950186',
    title: 'Ford v Ferrari',
    releaseYear: 2019,
    runtimeSeconds: 9120,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt3170832',
    title: 'Room',
    releaseYear: 2015,
    runtimeSeconds: 7080,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0118715',
    title: 'The Big Lebowski',
    releaseYear: 1998,
    runtimeSeconds: 7020,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0046438',
    title: 'Tokyo Story',
    releaseYear: 1953,
    runtimeSeconds: 8160,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0382932',
    title: 'Ratatouille',
    releaseYear: 2007,
    runtimeSeconds: 6660,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0075148',
    title: 'Rocky',
    releaseYear: 1976,
    runtimeSeconds: 7200,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0395169',
    title: 'Hotel Rwanda',
    releaseYear: 2004,
    runtimeSeconds: 7260,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt3315342',
    title: 'Logan',
    releaseYear: 2017,
    runtimeSeconds: 8220,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0019254',
    title: 'The Passion of Joan of Arc',
    releaseYear: 1928,
    runtimeSeconds: 6840,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt1895587',
    title: 'Spotlight',
    releaseYear: 2015,
    runtimeSeconds: 7740,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0091763',
    title: 'Platoon',
    releaseYear: 1986,
    runtimeSeconds: 7200,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0088247',
    title: 'The Terminator',
    releaseYear: 1984,
    runtimeSeconds: 6420,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt15097216',
    title: 'Jai Bhim',
    releaseYear: 2021,
    runtimeSeconds: 9840,
    certificate: 'TV-MA',
  },
  {
    url: 'https://www.imdb.com/title/tt0381681',
    title: 'Before Sunset',
    releaseYear: 2004,
    runtimeSeconds: 4800,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt1979320',
    title: 'Rush',
    releaseYear: 2013,
    runtimeSeconds: 7380,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0074958',
    title: 'Network',
    releaseYear: 1976,
    runtimeSeconds: 7260,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0036868',
    title: 'The Best Years of Our Lives',
    releaseYear: 1946,
    runtimeSeconds: 10200,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt0070047',
    title: 'The Exorcist',
    releaseYear: 1973,
    runtimeSeconds: 7320,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0092005',
    title: 'Stand by Me',
    releaseYear: 1986,
    runtimeSeconds: 5340,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0113247',
    title: 'La haine',
    releaseYear: 1995,
    runtimeSeconds: 5880,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0032138',
    title: 'The Wizard of Oz',
    releaseYear: 1939,
    runtimeSeconds: 6120,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0325980',
    title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
    releaseYear: 2003,
    runtimeSeconds: 8580,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0758758',
    title: 'Into the Wild',
    releaseYear: 2007,
    runtimeSeconds: 8880,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0317705',
    title: 'The Incredibles',
    releaseYear: 2004,
    runtimeSeconds: 6900,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0476735',
    title: 'My Father and My Son',
    releaseYear: 2005,
    runtimeSeconds: 6720,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0035446',
    title: 'To Be or Not to Be',
    releaseYear: 1942,
    runtimeSeconds: 5940,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt1028532',
    title: "Hachi: A Dog's Tale",
    releaseYear: 2009,
    runtimeSeconds: 5580,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt4016934',
    title: 'The Handmaiden',
    releaseYear: 2016,
    runtimeSeconds: 8700,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0032551',
    title: 'The Grapes of Wrath',
    releaseYear: 1940,
    runtimeSeconds: 7740,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt0058946',
    title: 'The Battle of Algiers',
    releaseYear: 1966,
    runtimeSeconds: 7260,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0107048',
    title: 'Groundhog Day',
    releaseYear: 1993,
    runtimeSeconds: 6060,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0245712',
    title: 'Amores Perros',
    releaseYear: 2000,
    runtimeSeconds: 9240,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0032976',
    title: 'Rebecca',
    releaseYear: 1940,
    runtimeSeconds: 7800,
    certificate: 'Approved',
  },
  {
    url: 'https://www.imdb.com/title/tt0059742',
    title: 'The Sound of Music',
    releaseYear: 1965,
    runtimeSeconds: 10320,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0061512',
    title: 'Cool Hand Luke',
    releaseYear: 1967,
    runtimeSeconds: 7620,
    certificate: 'GP',
  },
  {
    url: 'https://www.imdb.com/title/tt0048473',
    title: 'Pather Panchali',
    releaseYear: 1955,
    runtimeSeconds: 7500,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0129167',
    title: 'The Iron Giant',
    releaseYear: 1999,
    runtimeSeconds: 5160,
    certificate: 'PG',
  },
  {
    url: 'https://www.imdb.com/title/tt0025316',
    title: 'It Happened One Night',
    releaseYear: 1934,
    runtimeSeconds: 6300,
    certificate: 'Passed',
  },
  {
    url: 'https://www.imdb.com/title/tt1454029',
    title: 'The Help',
    releaseYear: 2011,
    runtimeSeconds: 8760,
    certificate: 'PG-13',
  },
  {
    url: 'https://www.imdb.com/title/tt0053198',
    title: 'The 400 Blows',
    releaseYear: 1959,
    runtimeSeconds: 5940,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0060827',
    title: 'Persona',
    releaseYear: 1966,
    runtimeSeconds: 4980,
    certificate: 'Not Rated',
  },
  {
    url: 'https://www.imdb.com/title/tt0079470',
    title: 'Life of Brian',
    releaseYear: 1979,
    runtimeSeconds: 5640,
    certificate: 'R',
  },
  {
    url: 'https://www.imdb.com/title/tt0103639',
    title: 'Aladdin',
    releaseYear: 1992,
    runtimeSeconds: 5400,
    certificate: 'G',
  },
  {
    url: 'https://www.imdb.com/title/tt0099348',
    title: 'Dances with Wolves',
    releaseYear: 1990,
    runtimeSeconds: 10860,
    certificate: 'PG-13',
  },
]
